

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: | 
            echo "JAVA VERSION "
            java -version
    displayName: JAVA VERSION
  - script: |
            sudo apt update
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 21.0.2-oracle
            sdk use java 21.0.2-oracle 
            mvn clean package
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'vm2-ssh'
      sourceFolder: '.'
      contents: 'docker-compose.yml'
      readyTimeout: '20000'