# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: | 
            echo "JAVA VERSION "
            java -version
    displayName: JAVA VERSION
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '17'
      jdkArchitectureOption: 'x86'
      jdkSourceOption: 'PreInstalled'
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'vm2-ssh'
      sourceFolder: '.'
      contents: 'docker-compose.yml'
      readyTimeout: '20000'