

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: | 
            echo "JAVA VERSION "
            java -version
    displayName: JAVA VERSION
  - script: |
            sudo apt update
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 17.0.9-tem
            sdk use java 17.0.9-tem
            java -version
            mvn clean package -DskipTests=true
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'vm2-ssh'
      sourceFolder: 'target/order-registration-0.0.1-SNAPSHOT.jar'
      contents: 'docker-compose.yml'
      readyTimeout: '20000'