

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: | 
            echo "JAVA VERSION "
            java -version
    displayName: JAVA VERSION
  - script: |
            sudo apt update
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install java 
  
  - script: | 
            echo "JAVA VERSION "
            java -version
    displayName: JAVA NEW VERSION

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'vm2-ssh'
      sourceFolder: '.'
      contents: 'docker-compose.yml'
      readyTimeout: '20000'