spring:
  config:
    use-legacy-processing: true
  profiles:
    active: staging
---
spring:
  profiles: development
  web:
    cors:
      allowed-origins: 'http://localhost:4200'
      allowed-methods: '*'
      allowed-headers: '*'
  data:
    mongodb:
      host: localhost
      port:  27017
      database: order-registration
      auto-index-creation: on
---
spring:
  profiles: staging
  web:
    cors:
      allowed-origins: 'http://localhost:4200'
      allowed-methods: '*'
      allowed-headers: '*'
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://${USER}:${PASSWORD}@cluster0.0wakd.mongodb.net/order-registration?retryWrites=true&w=majority}
---
spring:
  profiles: production
  web:
    cors:
      allowed-origins: 'http://localhost:4200'
      allowed-methods: '*'
      allowed-headers: '*'
  data:
    mongodb:
      uri: ${MONGODB_URI}
