spring:
  web:
    cors:
      allowed-origins: ${ALLOWED_HOST:http://localhost:4200}
      allowed-methods: '*'
      allowed-headers: '*'
  data:
    mongodb:
      uri: ${MONGODB_URI}
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}