# This Dockerfile its just to development mode, they will be replaced by another file which will contain
# the main configurations to starter the application in stagin or production environmemnt
FROM mongo
ENV MONGO_INITDB_DATABASE order-registration